apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - k3s-server
      containers:
      - name: nginx
        image: jc21/nginx-proxy-manager
        resources: {}
        ports:
        - containerPort: 80
          hostIP: 10.90.91.100
          hostPort: 80
        volumeMounts:
        - name: config
          mountPath: /data
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: nginx-config