apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft
spec:
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft     
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - k3s-worker-2
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000                   
      containers:
      - name: minecraft
        image: itzg/minecraft-server
        command:
          - sleep
        args: 
          - "14200"
        env:
          - name: EULA
            value: "TRUE"
          - name: TYPE
            value: SPIGOT
          - name: VERSION
            value: 1.19.2
          - name: DEBUG
            value: "true"
        resources:
          requests:
            cpu: 2000m
        # livenessProbe:
        #   exec:
        #     command: ["mc-health"]
        #   initialDelaySeconds: 120
        #   periodSeconds: 60
        # readinessProbe:
        #   exec:
        #     command: ["mc-health"]
        #   initialDelaySeconds: 20
        #   periodSeconds: 10
        #   failureThreshold: 12
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: data