apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:zhcIBErfMYZc1swxuryC,iv:R7C6y0txpPp1avWjsvDFJ6jo8vPONxgIIDS+yFajRbc=,tag:kjegn8sqTf91quY9LtTJ+g==,type:str]
    SECRET_EMAIL: ENC[AES256_GCM,data:A6jrFMVMvwEG41q4snHzEoDS2/sRng==,iv:oNEHn1XJ55wtjPMDtBita3YQqS5HCUSjrRSe31ON2Ss=,tag:R4o9VBJ5cqbYS0pnyzL9hA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-02-07T16:11:54Z"
    mac: ENC[AES256_GCM,data:J7pKM2Qyn1wFTdRSmeXDAx9rsXEmI4Ji4Eeku9isJ70RMhZnts02WMU8eTo6SCPQVvvXfCDUThrA4Kg5ggr+9P/GbRtFEtWqNM8c4gw/5CJKzkuR/OOeNUWyPLWxEeYvN771H9l39Su3E+lhlvNyNkbHe0HZeWZWvlZQ7y8Bgqg=,iv:3ZCLbnxCakRstAxuviML/RqIKyR11dlU7J6RhZM+mJM=,tag:Yot3aUj8uLPhzn4g3GgWRQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
