apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:/CELeAJ3cSCqcwmzZEBC,iv:EYYunf/uP8qbR6K37ZpZvz84njSuKTt2eQ9V0+bFXhA=,tag:aipmGha5yF+WzUoyo3An9w==,type:str]
    SECRET_EMAIL: ENC[AES256_GCM,data:s17aeyaVP7P3ELhGLnpm/9HS81KXPw==,iv:UthUP9yC6LRQtJ9zDMIDcNEzxFq0+USldf6lViRuHb8=,tag:9wXjDIyBgUc3j8Evu+4Daw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-02-07T16:07:36Z"
    mac: ENC[AES256_GCM,data:dGOYGisOxQuztkwzA3gCm/gHnOlXzychfsJWzvIc4vjS+BeWMwwVHGng31N5FY9qAbu17cbEFf5lkEB0muhRR7bar+eF6RuY/sQuAlXiTreQJCew7cQIKD7KiUInWPtqqheEV+RtWHKpp6ZAQeUK8DZFPP9I4zxThaprqq4wZcg=,iv:NsVstbnzgjYShxXo6YFEYYdT1OXjWjaa6xN0rNvEPeg=,tag:sOwO+KkE9g/u69hZ2Ao8Vg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
