---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: radarr
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"  
spec:
  path: ./clusters/homelab/media/radarr/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 1m
  retryInterval: 1m
  timeout: 3m