---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 45.0.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    alertmanager:
      alertmanagerSpec:
        nodeSelector:
          kubernetes.io/hostname: k3s-server
    grafana:
    prometheusOperator:
      admissionWebhooks:
        patch:
          nodeSelector:
            kubernetes.io/hostname: k3s-server
      nodeSelector:
        kubernetes.io/hostname: k3s-server
    prometheus:
      prometheusSpec: 
        nodeSelector:
          kubernetes.io/hostname: k3s-server
