apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
spec:
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - k3s-worker-1
      containers:
      - name: qbittorrent
        image: lscr.io/linuxserver/qbittorrent
        env:
          - name: TZ
            value: ${SECRET_TIMEZONE}
          - name: WEBUI_PORT
            value: "8080"
        resources: {}
        ports:
        - containerPort: 8080
        - containerPort: 30666
        volumeMounts:
        - name: config
          mountPath: /config
        - name: nfs
          mountPath: /mnt/nfs
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: qbittorrent-config
      - name: nfs
        persistentVolumeClaim:
          claimName: nfs