apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
spec:
  selector:
    app: qbittorrent
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent-udp
spec:
  type: NodePort
  selector:
    app: qbittorrent
  ports:
  - port: 30666
    targetPort: 30666