apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1500Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1500Gi