apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-path
  resources:
    requests:
      storage: 1500Gi