---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rancher
  namespace: cattle-system
spec:
  interval: 15m
  chart:
    spec:
      chart: rancher
      version: 4.4.2
      sourceRef:
        kind: HelmRepository
        name: rancher-latest
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    hostname: rancher.mgmt.lan