apiVersion: apps/v1
kind: Deployment
metadata:
  name: jackett
spec:
  selector:
    matchLabels:
      app: jackett
  template:
    metadata:
      labels:
        app: jackett
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - k3s-worker-1
      containers:
      - name: jackett
        image: lscr.io/linuxserver/jackett
        env:
          - name: TZ
            value: ${SECRET_TIMEZONE}
        resources: {}
        ports:
        - containerPort: 9117
        volumeMounts:
        - name: config
          mountPath: /config
        - name: nfs
          mountPath: /mnt/nfs
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: jackett-config
      - name: nfs
        persistentVolumeClaim:
          claimName: nfs