---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: jellyfin
  namespace: flux-system
spec:
  path: ./clusters/homelab/media/jellyfin/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 1m
  retryInterval: 1m
  timeout: 3m