apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
spec:
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - k3s-worker-1   
      containers:
      - name: sonarr
        image: lscr.io/linuxserver/radarr
        env:
          - name: TZ
            value: ${SECRET_TIMEZONE}
        resources: {}
        ports:
        - containerPort: 7878
        volumeMounts:
        - name: config
          mountPath: /config
        - name: nfs
          mountPath: /mnt/nfs
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: radarr-config
      - name: nfs
        persistentVolumeClaim:
          claimName: nfs