apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  labels:
    substitution.flux.home.arpa/enabled: "true"  
spec:
  acme:
    email: "${SECRET_EMAIL}"
    preferredChain: ''
    privateKeySecretRef:
      name: issuer-account-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - http01:
          ingress:
            class: nginx