---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: sonarr
  namespace: media
spec:
  path: ./clusters/homelab/media/sonarr/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 1m
  retryInterval: 1m
  timeout: 3m