---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  path: ./clusters/homelab/cert-manager/cert-manager/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: cert-manager
      namespace: cert-manager
  interval: 60m
  retryInterval: 5m
  timeout: 3m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cert-manager-issuers
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"    
spec:
  dependsOn:
    - name: cert-manager
  path: ./clusters/homelab/cert-manager/cert-manager/issuers
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 60m
  retryInterval: 5m
  timeout: 3m