---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: nfs-provisioner
  namespace: flux-system
spec:
  path: ./clusters/homelab/nfs-provisioner/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: nfs-provisioner
      namespace: nfs-provisioner
  interval: 60m
  retryInterval: 5m
  timeout: 3m