apiVersion: apps/v1
kind: Deployment
metadata:
  name: tdarr
spec:
  selector:
    matchLabels:
      app: tdarr
  template:
    metadata:
      labels:
        app: tdarr
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - k3s-worker-1
      containers:
      - name: tdarr
        image: ghcr.io/haveagitgat/tdarr
        env:
          - name: TZ
            value: Africa/Tunis
          - name: serverIP
            value: 0.0.0.0
          - name: serverPort
            value: "8266"
          - name: webUIPort
            value: "8265"
          - name: internalNode
            value: "true"
          - name: nodeID
            value: InternalNode
        resources: {}
        ports:
        - containerPort: 8266
        - containerPort: 8265
        volumeMounts:
        - name: config
          mountPath: /app/configs
        - name: data
          mountPath: /data
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: tdarr-config
      - name: data
        persistentVolumeClaim:
          claimName: data