---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: plex
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  path: ./clusters/homelab/media/plex/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 60m
  retryInterval: 5m
  timeout: 3m